platform: linux

image_resource:
  type: docker-image
  source:
    repository: jchesterpivotal/concourse-build-resource
    tag: v0.7.1

inputs:
- name: build

run:
  path: /opt/tasks/show-resources
