#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

version=$(cat image-version/version)

echo
echo Updating tags in README and utility tasks to v${version}
echo

git clone concourse-build-resource-repo updated-tags-repo

pushd updated-tags-repo
    grep -rl 'tag: v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+' . --exclude-dir=.git | xargs sed -i "s/tag: v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+/tag: v$version/g"

    grep -rl 'tag: v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+' . --exclude-dir=.git | xargs git add
    git status --verbose
    git commit -m "Update README.md and utility tasks to v$version" \
               -m "This commit is made automatically by the 'shipit' job." \
               -m "[skip ci]"
    git --no-pager log -1
popd

echo
echo Done.
echo
