platform: linux

image_resource:
  type: docker-image
  source:
    repository: samueldebruyn/debian-git

inputs:
- name: release-version
- name: concourse-build-resource-repo

outputs:
- name: updated-tags-repo

params:
  GIT_COMMITTER_NAME:
  GIT_COMMITTER_EMAIL:
  GIT_AUTHOR_NAME:
  GIT_AUTHOR_EMAIL:

run:
  path: concourse-build-resource-repo/ci/tasks/update-tags/run
