resources: ###########################################################################################

- name: concourse-build-resource-repo
  type: git
  check_every: 10m
  source:
    uri: git@github.com:jchesterpivotal/concourse-build-resource.git
    branch: master
    private_key: ((github-robot-key))
    git_config:
    - name: user.name
      value: Jacques Chester
    - name: user.email
      value: jchester+githubrobot@pivotal.io

- name: release-image
  type: docker-image
  source:
    repository: jchesterpivotal/concourse-build-resource
    username: jchesterpivotal
    password: ((dockerhub-password))

- name: release-version
  type: semver
  source:
    driver: gcs
    bucket: ((gcs-bucket-name))
    key: concourse-build-resource-version
    json_key: ((gcp-service-account-json-key))
    initial_version: 0.8.0-rc.2

- name: github-release
  type: github-release
  source:
    owner: jchesterpivotal
    repository: concourse-build-resource
    access_token: ((github-access-token))

jobs: #############################################################################################

- name: test
  public: true
  plan:
  - get: concourse-build-resource-repo
    trigger: true
    version: every
  - task: run-test
    file: concourse-build-resource-repo/ci/tasks/test/task.yml

- name: build-image
  public: true
  serial_groups: [build-and-release]
  plan:
  - aggregate:
    - get: concourse-build-resource-repo
      trigger: true
      version: every
      passed: [test]
    - put: release-version
      params: { pre: rc }
  - task: build-binaries
    file: concourse-build-resource-repo/ci/tasks/build/task.yml
    input_mapping: { version: release-version }
  - put: release-image
    params:
      dockerfile: concourse-build-resource-repo/ci/Dockerfile
      build: .
      tag_file: release-version/version
      tag_as_latest: false
      tag_prefix: v

- name: shipit
  public: true
  serial_groups: [build-and-release]
  plan:
  - aggregate:
    - get: concourse-build-resource-repo
      passed: [build-image]
    - get: release-image
      passed: [build-image]
      params: {save: true}
    - get: release-version
      passed: [build-image]
      params: { bump: final }

  - task: update-tags-in-files
    file: concourse-build-resource-repo/ci/tasks/update-tags/task.yml
    params:
      GIT_COMMITTER_NAME: Jacques Chester
      GIT_COMMITTER_EMAIL: jchester+githubrobot@pivotal.io
      GIT_AUTHOR_NAME: Jacques Chester
      GIT_AUTHOR_EMAIL: jacques@chester.id.au
  - put: concourse-build-resource-repo
    params:
      repository: updated-tags-repo

  - aggregate:
    - put: release-image
      params:
        load: release-image
        tag_file: release-version/version
        tag_as_latest: true
        tag_prefix: v
    - put: release-version
      params: { file: release-version/version }
    - put: github-release
      params:
        name: release-version/version
        tag: release-version/version
        commitish: concourse-build-resource-repo/.git/ref
        tag_prefix: v

- name: bump-patch-version
  public: true
  plan:
  - put: release-version
    params: { bump: patch }

- name: bump-minor-version
  public: true
  plan:
  - put: release-version
    params: { bump: minor }
