resources: ###########################################################################################

- name: concourse-build-resource-repo
  type: git
  check_every: 10m
  source:
    uri: https://github.com/jchesterpivotal/concourse-build-resource.git

- name: release-image
  type: docker-image
  source:
    repository: gcr.io/cf-elafros-dog/concourse-build-resource
    username: _json_key
    password: ((gcp-service-account-json-key))

- name: image-version
  type: semver
  source:
    driver: gcs
    bucket: us.artifacts.cf-elafros-dog.appspot.com
    key: concourse-build-resource-version
    json_key: ((gcp-service-account-json-key))
    initial_version: 0.2.0

- name: github-release
  type: github-release
  source:
    owner: jchesterpivotal
    repository: concourse-build-resource
    access_token: ((github-access-token))

jobs: #############################################################################################

- name: test
  public: true
  plan:
  - get: concourse-build-resource-repo
    trigger: true
    version: every
  - task: run-test
    file: concourse-build-resource-repo/ci/tasks/test/task.yml

- name: build-image
  public: true
  serial_groups: [build-and-release]
  plan:
  - aggregate:
    - get: concourse-build-resource-repo
      trigger: true
      version: every
      passed: [test]
    - put: image-version
      params: { pre: rc }
  - task: build-binaries
    file: concourse-build-resource-repo/ci/tasks/build/task.yml
  - put: release-image
    params:
      dockerfile: concourse-build-resource-repo/ci/Dockerfile
      build: .
      tag_file: image-version/version
      tag_as_latest: false
      tag_prefix: v

- name: shipit
  public: true
  serial_groups: [build-and-release]
  plan:
  - aggregate:
    - get: concourse-build-resource-repo
      passed: [build-image]
    - get: release-image
      passed: [build-image]
      params: {save: true}
    - get: image-version
      passed: [build-image]
      params: { bump: final }
  - put: release-image
    params:
      load: release-image
      tag_file: image-version/version
      tag_as_latest: true
      tag_prefix: v
  - put: image-version
    params: { file: image-version/version }
  - put: github-release
    params:
      name: image-version/version
      tag: image-version/version
      commitish: concourse-build-resource-repo/.git/ref
      tag_prefix: v

- name: bump-patch-version
  public: true
  plan:
  - put: image-version
    params: { bump: patch }

- name: bump-minor-version
  public: true
  plan:
  - put: image-version
    params: { bump: minor }
