resources: ###########################################################################################

- name: concourse-build-resource-repo
  type: git
  check_every: 10m
  source:
    uri: https://github.com/jchesterpivotal/concourse-build-resource.git

- name: release-image
  type: docker-image
  source:
    repository: gcr.io/cf-elafros-dog/concourse-build-resource
    username: _json_key
    password: ((gcp-service-account-json-key))

- name: image-version
  type: semver
  source:
    driver: gcs
    bucket: us.artifacts.cf-elafros-dog.appspot.com
    key: concourse-build-resource-version
    json_key: ((gcp-service-account-json-key))
    initial_version: 0.1.0

jobs: #############################################################################################

- name: test
  public: true
  plan:
  - get: concourse-build-resource-repo
    trigger: true
    version: every
  - task: run-test
    file: concourse-build-resource-repo/ci/tasks/test/task.yml

- name: build-image
  public: true
  plan:
  - aggregate:
    - get: concourse-build-resource-repo
      trigger: true
      version: every
      passed: [test]
    - put: image-version
      params: { pre: rc }
  - task: build-binaries
    file: concourse-build-resource-repo/ci/tasks/build/task.yml
  - put: release-image
    params:
      dockerfile: concourse-build-resource-repo/ci/Dockerfile
      build: .
      tag_file: image-version/version
      tag_as_latest: true
