#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo Testing

export GO111MODULE=on
export GOOS=linux
export GOARCH=amd64

pushd concourse-build-resource-repo
    go test -v -mod=vendor  ./...
popd

echo Done.
